package frms.bre.panels;

import javax.swing.table.*;

public class BRESummary extends javax.swing.JPanel {

    public static final String[] columns_transaction = {
        "date", "emp_num", "itemnumber", "qty", "datereserved", "dateborrowed", "duedate",
        "datereturned"
    };
    public static final String[] colh_transaction = {
        "Transaction Date", "Employee Number", "Item Number", "Quantity",
        "Date Reserved", "Date Borrowed", "Due Date", "Date Returned"
    };

    /**
     * Creates new form BRESummary
     */
    public BRESummary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSummary = new javax.swing.JTable();
        lblSummaryTitle = new javax.swing.JLabel();

        tblSummary.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblSummary.setModel(new DefaultTableModel());
        tblSummary.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblSummary);

        lblSummaryTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSummaryTitle.setText("Summary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSummaryTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSummaryTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSummaryTitle;
    public static javax.swing.JTable tblSummary;
    // End of variables declaration//GEN-END:variables
}
